name: Updates

on:
  schedule:
  - cron: '*/38 * * * *'

jobs: 
  download_updates:
    name: Downloads the daily new updates of the israeli health ministry 
    runs-on: windows-latest
    steps:
    - name: Access user
      env: 
        USER_EMAIL: "idanraman@users.noreply.github.com"
        USER_NAME: "Idanraman"
      run: |
        git config --global user.email $USER_EMAIL
        git config --global user.name $USER_NAME
      shell: bash
    - name: Clone git
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: true
    - name: Run update script
      run: |
        pip install telethon
        pip install tabula-py
        pip install pandas
        pip install translate
        pip install beautifulsoup4
        python update_files.py
      working-directory: ./src/
    - name: Push new files
      run: |
        git config --global user.name 'Idanraman'
        git config --global user.email 'idanraman@users.noreply.github.com'
        git status
        git add .
        git commit -am "Automated files collection"
        git push
      working-directory: /
